import 'package:magazine_luiza/models/product.dart';

List<Product> listOfProducts = [
  Product(
    photo: "assets/images/celular.jpg",
    name: "Smartphone Samsung Galaxy A71 128GB Azul 6GB RAM",
    descripition: "Tela 6,7' Câm. Quádrupla Câm. + Selfie 32MP",
    price: 1979.97,
    parcel: 10,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/geladeira.jpg",
    name: "Geladeira Brastemp Frost Free Duplex Evox",
    descripition: "375L BRM45 HKANA",
    price: 2698.00,
    parcel: 10,
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/fritadeira.jpg",
    name: "Fritadeira Elétrica sem Óleo/Air Fryer Nell Smart",
    descripition: "Preta 2,4L com Timer",
    price: 229.90,
    parcel: 5,
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/computador.jpg",
    name: "PC Gamer Neologic Start NLI81426 Ryzen 3 2200G 8GB",
    descripition: "Radeon Vega 8 integrado + SSD 240GB",
    price: 4859.00,
    parcel: 12,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/microfone.jpg",
    name: "Microfone de Mesa Condensador para Celular, Computador e Notebook",
    descripition: "Redshock",
    price: 99.90,
    parcel: 3,
    isFavorite: false,
  ),
  Product(
    photo: "assets/images/ventilador.jpg",
    name: "Ventilador de Parede e Mesa Mondial Maxi Power",
    descripition: "NV-15-6P-FB 30cm 3 Velocidades",
    price: 89.90,
    parcel: 2,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/drone.jpg",
    name: "Drone Multilaser Eagle FPV",
    descripition: "Câmera HD Flips 360",
    price: 1979.97,
    parcel: 10,
    isFavorite: false,
  ),
];
